# Generated by Django 4.2 on 2023-05-02 00:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('date', models.DateField(verbose_name='meeting date')),
                ('start_time', models.TimeField(default='00:00:00', verbose_name='start time')),
                ('end_time', models.TimeField(default='00:00:00', verbose_name='end time')),
                ('location', models.CharField(max_length=200)),
                ('agenda', models.CharField(max_length=200)),
                ('is_complete', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='meetings', to=settings.AUTH_USER_MODEL)),
                ('participants', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Meetings',
                'ordering': ['name', 'date', 'start_time', 'end_time'],
            },
        ),
    ]
